//* err: ContinueOutsideLoop
fn main() {
    continue;
}
