//* err: todo!
fn main() -> Bool {
    42
}

