//* err: todo!
fn main() {
    x = 2
}
